default_install_hook_types:
- pre-commit
- commit-msg
default_stages:
- pre-commit
exclude: ^docs/snippets/|vendor/|node_modules/|target/|v3/|invalid*
repos:
- repo: https://github.com/Goldziher/gitfluff
  rev: v0.8.0
  hooks:
  - id: gitfluff-lint
    args:
    - --write
    stages:
    - commit-msg
- repo: https://github.com/kreuzberg-dev/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-yaml
    args:
    - --allow-multiple-documents
  - id: check-case-conflict
  - id: rumdl-fmt
    exclude: \.ai-rulez/
  - id: oxfmt
  - id: actionlint
  - id: gh-actions-updater
  - id: typos
    args:
    - --force-exclude
